package edu.tamu.tcat.trc.resolver;

/**
 * Maintains a registry of {@link EntryResolver}s for the various entry types
 * defined by the system.
 */
public interface EntryResolverRegistry
{
   // TODO how to handle multiple matching registrations?

   /**
    * @param ref An {@link EntryId} for which to obtain a resolver
    * @return An {@link EntryResolver} that accepts the supplied reference.
    * @throws InvalidReferenceException If no registered resolver accepts
    *       the supplied reference.
    */
   <T> EntryResolver<T> getResolver(EntryId ref) throws InvalidReferenceException;


   /**
    * @param entry An TRC entry instance for which to obtain a resolver
    * @return An {@link EntryResolver} that accepts the supplied entry.
    * @throws InvalidReferenceException If no registered resolver accepts
    *       the supplied entry.
    */
   <T> EntryResolver<T> getResolver(T entry);

   /**
    *
    * @param ref An entry ref to tokenize
    * @return An opaque token that can be used to restore this reference.
    */
   String tokenize(EntryId ref);

   /**
    * @param token A token to decode as generated by {@link #tokenize(EntryId)}
    * @return The decoded entry reference for this token.
    * @throws IllegalArgumentException If the supplied token cannot be parsed.
    * @throws InvalidReferenceException If the docoded reference is not associated with
    *    a registered {@link EntryResolver}
    */
   EntryId decodeToken(String token) throws IllegalArgumentException, InvalidReferenceException;
}
